apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-name
  region: ap-northeast-2
  version: "1.27"

vpc:
  id: vpc-001d230c69000f6f9
  subnets:
    private:
      private-a: {id: subnet-0f5aaaa2e152ff697}
      private-b: {id: subnet-0fa96d15b8230eafc}
      private-c: {id: subnet-031a299615e513f77}

managedNodeGroups:
  - name: app
    instanceType: c5.large
    minSize: 2
    labels: { dedicated: app }
    subnets:
      - private-a
      - private-b
      - private-c
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        albIngress: true
        cloudWatch: true
        autoScaler: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
