apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster
  region: ap-northeast-2
fargateProfiles:
  - name: fargate-profile
    selectors:
      - namespace: app
      - namespace: kube-system
      - namespace: default
