apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: apps
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [nano, micro, small]
    - key: "kubernetes.io/arch" # If not included, the webhook for the AWS Cloud Provider will default to amd64
      operator: In
      values: ["amd64"] # arm64
    - key: "karpenter.sh/capacity-type"         # optional, set to on-demand by default, spot if both are listed
      operator: In
      values: ["on-demand", "spot"] # ["on-demand", "spot"]
    - key: "topology.kubernetes.io/zone"      # 가용 영역
      operator: In
      values: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"] # add "ap-northeast-2d
        #    - key: node.kubernetes.io/instance-type
        #      operator: In
        #      values: ["m5.xlarge","m5.2xlarge"]
  providerRef:                                # optional, recommended to use instead of `provider`
    name: apps-provider
  taints:
    - key: dedicated
      value: app
      effect: NoSchedule
  ttlSecondsAfterEmpty: 300                    # optional, but never scales down if not set
  # If omitted, the feature is disabled and nodes will never expire.  If set to less time than it requires for a node
  # to become ready, the node may expire before any pods successfully start.
  # ttlSecondsUntilExpired: 2592000        # 30 Days = 60 * 60 * 24 * 30 Seconds;
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: apps-provider
spec:
  amiFamily: Bottlerocket
  subnetSelector:                             # required
    karpenter.sh/discovery: cluster
  securityGroupSelector:                      # required, when not using launchTemplate
    karpenter.sh/discovery: cluster
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 20Gi
        deleteOnTermination: true
  tags:
    Name: app-node
    node.k8s.aws/dedicated: app # dedicated: app이라는 값을 노드에 label, ec2에 태그 할당
  userData: ""
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
