apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: test
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam:111111:role/eks-test-role
  name: test
  namespace: dev



  ---
  {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::11111:oidc-providder/oidc.eks.ap-northeast-2.amazonaws.com/id/1234"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.ap-northeast-2.amazonaws.com/id/1234:sub": "system:serviceaccount:stage:test-sa"
                }
            }
        }
    ]
}
