apiVersion: v1
kind: Service
metadata:
  name: match
  namespace: skills
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
spec:
  selector:
    app: match
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
